export default {
    "RS UMUM DAERAH  DR. ZAINOEL ABIDIN": require("../assets/images/rs-u-daerah-dr-zainoel-abidin.jpg"),
    "RS UMUM DAERAH CUT MEUTIA KAB. ACEH UTARA": require("../assets/images/rs-u-daerah-cut-meutia-kab-aceh-utara.jpg"),
    "RSUP SANGLAH": require("../assets/images/rsup-sanglah.jpg"),
    "RS UMUM DAERAH KAB. BULELENG": require("../assets/images/rs-u-daerah-kab-buleleng.jpg"),
    "RS UMUM DAERAH SANJIWANI GIANYAR": require("../assets/images/rs-u-daerah-sanjiwani-gianyar.jpg"),
    "RS UMUM DAERAH TABANAN": require("../assets/images/rs-u-daerah-tabanan.jpg"),
    "RS UMUM DAERAH KABUPATEN TANGERANG": require("../assets/images/rs-u-daerah-kabupaten-tangerang.jpg"),
    "RS UMUM DAERAH DR. DRAJAT PRAWIRANEGARA": require("../assets/images/rs-u-daerah-dr-draja-prawiranegara.jpg"),
    "RS UMUM DAERAH DR. M. YUNUS BENGKULU": require("../assets/images/rs-u-daerah-dr-m-yunus-bengkulu.jpg"),
    "RS UMUM DAERAH ARGA MAKMUR": require("../assets/images/rs-u-daerah-arga-makmur.jpg"),
    // "RS UMUM DAERAH HASANUDDIN DAMRAH MANNA": require("../assets/images/rs-u-daerah-hasanuddin-damrah-manna.jpg"),
    // "RS UMUM DAERAH PANEMBAHAN SENOPATI": require("../assets/images/rs-u-daerah-panembahan-senopati.jpg"),
    // "RS UMUM DAERAH WATES": require("../assets/images/rs-u-daerah-wates.jpg"),
    // "RS UMUM DAERAH KOTA YOGYAKARTA": require("../assets/images/rs-u-daerah-kota-yogyakarta.jpg"),
    // "RSUP DR. SARDJITO": require("../assets/images/rsup-dr-sardjito.jpg"),
    // "RS UMUM AL DR MINTOHARJO": require("../assets/images/rs-u-al-dr-mintoharjo.jpg"),
    // "RS UMUM PAD GATOT SOEBROTO": require("../assets/images/rs-u-pad-gatot-soebroto.jpg"),
    // "RS UMUM BHAYANGKARA TK. I R.SAID SUKANTO": require("../assets/images/rs-u-bhayangkara-tk-1-rsaid-sukanto.jpg"),
    // "RSUP PERSAHABATAN": require("../assets/images/rsup-persahabatan.jpg"),
    // "RS PENYAKIT INFEKSI PROF. DR. SULIANTI SAROSO": require("../assets/images/rs-penyakit-infeksi-prof-dr-suliani-saroso.jpg"),
    // "RSUP FATMAWATI": require("../assets/images/rsup-fatmawati.jpg"),
    // "RS UMUM DAERAH PASAR MINGGU": require("../assets/images/rs-u-daerah-pasar-minggu.jpg"),
    // "RS UMUM DAERAH CENGKARENG": require("../assets/images/rs-u-daerah-cengkareng.jpg"),
    // "RS UMUM DAERAH PROF DR. H. ALOEI SABOE": require("../assets/images/rs-u-daerah-prof-dr-h-aloei-saboe.jpg"),
    // "RS UMUM DAERAH RADEN MATTAHER JAMBI": require("../assets/images/rs-u-daerah-raden-mattaher-jambi.jpg"),
    // "RS PARU DR. H. A. ROTINSULU": require("../assets/images/rs-paru-dr-h-a-rotinsulu.jpg"),
    // "RS UMUM PUSAT DR. HASAN SADIKIN": require("../assets/images/rs-u-pusat-dr-hasan-sadikin.jpg"),
    // "RS UMUM DAERAH DR. SLAMET GARUT": require("../assets/images/rs-u-daerah-dr-slamet-garut.jpg"),
    // "RS UMUM TK II DUSTIRA": require("../assets/images/rs-u-tk-ii-dustira.jpg"),
    // "RS PARU DR. M. GOENAWAN PARTOWIDIGDO": require("../assets/images/rs-paru-dr-m-goenawan-partowidigdo.jpg"),
    // "RS UMUM DAERAH  R SYAMSUDIN SH": require("../assets/images/rs-u-daerah-r-syamsudin-sh.jpg"),
    // "RS UMUM DAERAH GUNUNG JATI": require("../assets/images/rs-u-daerah-gunung-jati.jpg"),
    // "RS UMUM DAERAH KAB. INDRAMAYU": require("../assets/images/rs-u-daerah-kab-indramayu.jpg"),
    // "RS UMUM DAERAH K.R.M.T WONGSONEGORO": require("../assets/images/rs-u-daerah-k-r-m-t-wongsonnegoro.jpg"),
    // "RS UMUM PUSAT DR. KARIADI": require("../assets/images/rs-u-pusat-dr-kariadi.jpg"),
    // "RS UMUM DAERAH KRATON KAB. PEKALONGAN": require("../assets/images/rs-u-daerah-kraton-kab-pekalongan.jpg"),
    // "RS UMUM DAERAH KARDINAH": require("../assets/images/rs-u-daerah-kardinah.jpg"),
    // "RS UMUM PUSAT DR. SOERADJI TIRTONEGORO": require("../assets/images/rs-u-pusat-dr-soeradji-tirtonogoro.jpg"),
    // "RS UMUM DAERAH DR. SOESELO SLAWI KABUPATEN TEGAL": require("../assets/images/rs-u-daerah-dr-soeselo-slawi-kabupaten-tegal.jpg"),
    // "RS UMUM DAERAH PROF DR. MARGONO SOEKARJO PURWOKER": require("../assets/images/rs-u-daerah-prof-dr-margono-soekarjo-purwoker.jpg"),
    // "RS UMUM DAERAH  DR. H. SOEWONDO KENDAL": require("../assets/images/rs-u-daerah-dr-h-soewondo-kendal.jpg"),
    // "RS UMUM DAERAH DR. MOEWARDI SURAKARTA": require("../assets/images/rs-u-daerah-dr-moewardi-surakarta.jpg"),
    // "RS UMUM DAERAH TIDAR": require("../assets/images/rs-u-daerah-tidar.jpg"),
    // "RSUD BANYUMAS": require("../assets/images/rsud-banyumas.jpg"),
    // "RS PARU DR. ARIO WIRAWAN": require("../assets/images/rs-paru-dr-ario-wirawan.jpg"),
    // "RS UMUM DAERAH DR. LOEKMONO HADI": require("../assets/images/rs-u-daerah-dr-loekmono-hadi.jpg"),
    // "RS UNIVERSITAS AIRLANGGA": require("../assets/images/rs-universitas-airlangga.jpg"),
    // "RS UMUM DAERAH DR. SOETOMO": require("../assets/images/rs-u-daerah-dr-soetomo.jpg"),
    // "RS UMUM DAERAH DR. SOEDONO MADIUN": require("../assets/images/rs-u-daerah-dr-soedono-madiun.jpg"),
    // "RS UMUM DAERAH DR. SAIFUL ANWAR": require("../assets/images/rs-u-daerah-dr-saiful-anwar.jpg"),
    // "RS UMUM DAERAH DR. R. KOESMA TUBAN": require("../assets/images/rs-u-daerah-dr-r-koesma-tuban.jpg"),
    // "RS UMUM DAERAH DR. R. SOSODORO DJATIKOESOEMO": require("../assets/images/rs-u-daerah-dr-r-sosodoro-djatikoesoemo.jpg"),
    // "RS UMUM DAERAH SIDOARJO": require("../assets/images/rs-u-daerah-sidoarjo.jpg"),
    // "RS UMUM DAERAH BLAMBANGAN": require("../assets/images/rs-u-daerah-blambangan.jpg"),
    // "RS UMUM DAERAH DR. SOEBANDI": require("../assets/images/rs-u-daerah-dr-soebandi.jpg"),
    // "RS UMUM DAERAH KABUPATEN KEDIRI": require("../assets/images/rs-u-daerah-kabupaten-kediri.jpg"),
    // "RS UMUM DAERAH DR. ISKAK TULUNGAGUNG": require("../assets/images/rs-u-daerah-dr-iskak-tulungagung.jpg"),
    // "RS UMUM DAERAH DR. SOEDARSO PONTIANAK": require("../assets/images/rs-u-daerah-dr-soedarso-pontianak.jpg"),
    // "RS UMUM DAERAH ADE MUHAMMAD DJOEN SINTANG": require("../assets/images/rs-u-daerah-ade-muhammad-djoen-sintang.jpg"),
    // "RS UMUM DAERAH DR. AGOESDJAM KETAPANG": require("../assets/images/rs-u-daerah-dr-agoesdjam-ketapang.jpg"),
    // "RS UMUM DAERAH DR. ABDUL AZIZ": require("../assets/images/rs-u-daerah-dr-abdul-aziz.jpg"),
    // "RS UMUM DAERAH DR. RADEN SUDONO": require("../assets/images/rs-u-daerah-dr-raden-sudono.jpg"),
    // "RS UMUM DAERAH DAMAI": require("../assets/images/rs-u-daerah-damai.jpg"),
    // "RS UMUM DAERAH BONTANG": require("../assets/images/rs-u-daerah-bontang.jpg")
}
